export type StockTuple = [symbol: string, name: string];

export const US_STOCKS: StockTuple[] = [
  ['AAPL', 'Apple'],
  ['MSFT', 'Microsoft'],
  ['AMZN', 'Amazon'],
  ['NVDA', 'NVIDIA'],
  ['GOOGL', 'Alphabet A'],
  ['GOOG', 'Alphabet C'],
  ['META', 'Meta'],
  ['TSLA', 'Tesla'],
  ['BRK.B', 'Berkshire B'],
  ['UNH', 'UnitedHealth'],
  ['JPM', 'JPMorgan'],
  ['V', 'Visa'],
  ['JNJ', 'Johnson & Johnson'],
  ['XOM', 'Exxon Mobil'],
  ['MA', 'Mastercard'],
  ['PG', 'Procter & Gamble'],
  ['HD', 'Home Depot'],
  ['CVX', 'Chevron'],
  ['MRK', 'Merck'],
  ['ABBV', 'AbbVie'],
  ['LLY', 'Eli Lilly'],
  ['AVGO', 'Broadcom'],
  ['PEP', 'PepsiCo'],
  ['KO', 'Coca-Cola'],
  ['COST', 'Costco'],
  ['TMO', 'Thermo Fisher'],
  ['MCD', "McDonald's"],
  ['WMT', 'Walmart'],
  ['CSCO', 'Cisco'],
  ['ACN', 'Accenture'],
  ['ABT', 'Abbott'],
  ['DHR', 'Danaher'],
  ['BAC', 'Bank of America'],
  ['PFE', 'Pfizer'],
  ['CRM', 'Salesforce'],
  ['NKE', 'Nike'],
  ['DIS', 'Disney'],
  ['ADBE', 'Adobe'],
  ['NFLX', 'Netflix'],
  ['CMCSA', 'Comcast'],
  ['AMD', 'AMD'],
  ['INTC', 'Intel'],
  ['TXN', 'Texas Instruments'],
  ['QCOM', 'Qualcomm'],
  ['INTU', 'Intuit'],
  ['HON', 'Honeywell'],
  ['IBM', 'IBM'],
  ['AMGN', 'Amgen'],
  ['AMAT', 'Applied Materials'],
  ['CAT', 'Caterpillar'],
  ['GS', 'Goldman Sachs'],
  ['LOW', "Lowe's"],
  ['BA', 'Boeing'],
  ['GE', 'GE Aerospace'],
  ['SBUX', 'Starbucks'],
  ['BLK', 'BlackRock'],
  ['DE', 'Deere'],
  ['ISRG', 'Intuitive Surgical'],
  ['GILD', 'Gilead'],
  ['SYK', 'Stryker'],
  ['ADP', 'ADP'],
  ['BKNG', 'Booking'],
  ['MDLZ', 'Mondelez'],
  ['MMC', 'Marsh McLennan'],
  ['VRTX', 'Vertex'],
  ['ADI', 'Analog Devices'],
  ['LRCX', 'Lam Research'],
  ['PANW', 'Palo Alto'],
  ['REGN', 'Regeneron'],
  ['MU', 'Micron'],
  ['KLAC', 'KLA Corp'],
  ['SNPS', 'Synopsys'],
  ['CDNS', 'Cadence'],
  ['MRVL', 'Marvell'],
  ['CRWD', 'CrowdStrike'],
  ['FTNT', 'Fortinet'],
  ['DASH', 'DoorDash'],
  ['DDOG', 'Datadog'],
  ['ZS', 'Zscaler'],
  ['NET', 'Cloudflare'],
  ['SNOW', 'Snowflake'],
  ['PLTR', 'Palantir'],
  ['COIN', 'Coinbase'],
  ['SQ', 'Block'],
  ['SHOP', 'Shopify'],
  ['ROKU', 'Roku'],
  ['U', 'Unity'],
  ['RBLX', 'Roblox'],
  ['RIVN', 'Rivian'],
  ['LCID', 'Lucid'],
  ['NIO', 'NIO'],
  ['SOFI', 'SoFi'],
  ['HOOD', 'Robinhood'],
  ['PYPL', 'PayPal'],
  ['UBER', 'Uber'],
  ['LYFT', 'Lyft'],
  ['ABNB', 'Airbnb'],
  ['PINS', 'Pinterest'],
  ['SNAP', 'Snap'],
  ['TTD', 'Trade Desk'],
  ['MELI', 'MercadoLibre'],
  ['SE', 'Sea Ltd'],
  ['BABA', 'Alibaba'],
  ['JD', 'JD.com'],
  ['PDD', 'PDD Holdings'],
  ['TSM', 'TSMC'],
  ['ASML', 'ASML'],
  ['ARM', 'Arm Holdings'],
  ['SMCI', 'Super Micro'],
  ['DELL', 'Dell'],
  ['HPQ', 'HP'],
  ['ORCL', 'Oracle'],
  ['NOW', 'ServiceNow'],
  ['WDAY', 'Workday'],
  ['VEEV', 'Veeva'],
  ['TEAM', 'Atlassian'],
  ['HUBS', 'HubSpot'],
  ['BILL', 'Bill.com'],
  ['PATH', 'UiPath'],
  ['AI', 'C3.ai'],
  ['IONQ', 'IonQ'],
  ['RGTI', 'Rigetti'],
  ['QUBT', 'Quantum Computing'],
  ['GME', 'GameStop'],
  ['AMC', 'AMC'],
  ['BBBY', 'Bed Bath'],
  ['SPCE', 'Virgin Galactic'],
  ['F', 'Ford'],
  ['GM', 'General Motors'],
  ['TM', 'Toyota'],
  ['STLA', 'Stellantis'],
  ['WFC', 'Wells Fargo'],
  ['C', 'Citigroup'],
  ['MS', 'Morgan Stanley'],
  ['SCHW', 'Schwab'],
  ['T', 'AT&T'],
  ['VZ', 'Verizon'],
  ['TMUS', 'T-Mobile'],
  ['SPY', 'S&P 500 ETF'],
  ['QQQ', 'Nasdaq ETF'],
  ['IWM', 'Russell 2000 ETF'],
  ['DIA', 'Dow ETF'],
  ['ARKK', 'ARK Innovation'],
  ['SOXL', 'Semicon 3x Bull'],
  ['TQQQ', 'Nasdaq 3x Bull'],
  ['SQQQ', 'Nasdaq 3x Bear'],
  ['XLF', 'Financial ETF'],
  ['XLE', 'Energy ETF'],
  ['XLK', 'Tech ETF'],
  ['XLV', 'Health ETF'],
  ['ES=F', 'S&P 500 Futures'],
  ['NQ=F', 'Nasdaq Futures'],
  ['YM=F', 'Dow Futures'],
  ['GC=F', 'Gold Futures'],
  ['CL=F', 'Crude Oil Futures'],
  ['SI=F', 'Silver Futures'],
];

export const STOCK_CATEGORIES: Record<string, string[]> = {
  Tech: ['AAPL', 'MSFT', 'NVDA', 'GOOGL', 'META', 'AMZN', 'TSLA', 'AMD', 'INTC', 'AVGO', 'ORCL', 'CRM', 'ADBE', 'NFLX', 'QCOM'],
  Finance: ['JPM', 'BAC', 'GS', 'MS', 'V', 'MA', 'WFC', 'C', 'SCHW', 'BLK', 'PYPL', 'SQ', 'SOFI', 'HOOD', 'COIN'],
  Healthcare: ['UNH', 'JNJ', 'LLY', 'MRK', 'ABBV', 'PFE', 'TMO', 'ABT', 'AMGN', 'GILD', 'ISRG', 'SYK', 'VRTX', 'REGN', 'DHR'],
  Consumer: ['WMT', 'COST', 'HD', 'MCD', 'NKE', 'SBUX', 'DIS', 'PG', 'KO', 'PEP', 'LOW', 'ABNB', 'UBER', 'BKNG', 'DASH'],
  Energy: ['XOM', 'CVX', 'CL=F', 'GC=F'],
  ETFs: ['SPY', 'QQQ', 'IWM', 'DIA', 'ARKK', 'TQQQ', 'SQQQ', 'SOXL', 'XLF', 'XLE', 'XLK', 'XLV'],
  'Meme/Speculative': ['GME', 'AMC', 'PLTR', 'RIVN', 'LCID', 'NIO', 'SPCE', 'IONQ', 'RGTI', 'QUBT'],
  Futures: ['ES=F', 'NQ=F', 'YM=F', 'GC=F', 'CL=F', 'SI=F'],
};
